#!/usr/bin/env ruby
# frozen_string_literal: true

lib_path = File.expand_path('../lib', __dir__)
$:.unshift(lib_path) if !$:.include?(lib_path)
require 'dru'

Signal.trap('INT') do
  exit(1)
end

begin
  Dru::CLI.start(Dru::Argv.parse)
rescue Dru::CLI::Error
  exit 1
end
